/* automatically generated by JSCoverage - do not edit */
if (typeof _$jscoverage === 'undefined') _$jscoverage = {};
if (! _$jscoverage['nu.js']) {
  _$jscoverage['nu.js'] = [];
  _$jscoverage['nu.js'][1] = 0;
  _$jscoverage['nu.js'][2] = 0;
  _$jscoverage['nu.js'][3] = 0;
  _$jscoverage['nu.js'][4] = 0;
  _$jscoverage['nu.js'][7] = 0;
}
_$jscoverage['nu.js'][1]++;
function nu() {
  _$jscoverage['nu.js'][2]++;
  var obj = Object.create(this.prototype);
  _$jscoverage['nu.js'][3]++;
  this.apply(obj, arguments);
  _$jscoverage['nu.js'][4]++;
  return obj;
}
_$jscoverage['nu.js'][7]++;
module.exports = nu;
_$jscoverage['nu.js'].source = ["function nu() {","  var obj = Object.create(this.prototype);","  this.apply(obj, arguments);","  return obj;","}","","module.exports = nu;"];
